# https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/master/charts/nfs-server-provisioner/values.yaml

persistence:
  enabled: true
  storageClass: ""
  size: "30Gi"

storageClass:
  create: true
  name: nfs

priorityClass:
  create: true
  value: 50


resources:
  limits:
   memory: 2Gi
  requests:
   cpu: 1
   memory: 1Gi

# The nfs server should always work on this node to reach
# the same hostpath, diger nodelar 2 ve 3 seklinde sayilari da 
# iceriyor isimlerinde, o yuzdena sagidaki sadece bir node'u isaret ediyor.
nodeSelector:
  kubernetes.io/hostname: 10.10.10.201