---
apiVersion: v1
kind: Service
metadata:
  name: inavitas-kafka-srv
  namespace: inavitas-staging
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - port: 9094
      nodePort: 31072
