---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: inavitas-staging
  labels:
    app: kafka
spec:
  replicas: 3
  serviceName: inavitas-kafka-srv
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.13-2.8.1
          ports:
            - containerPort: 9094
          env:
            - name: HOSTNAME_COMMAND
              value: "echo \"$HOSTNAME.inavitas.io\""
            - name: BROKER_ID_COMMAND
              value: "hostname | awk -F'-' '{print $2}'"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-0.inavitas-zookeeper-srv:2181,\
                      zookeeper-1.inavitas-zookeeper-srv:2181,\
                      zookeeper-2.inavitas-zookeeper-srv:2181"
            - name: KAFKA_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://0.0.0.0:9094"
              # Ad
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:31072"
              # Bu dogru
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_LOG_DIRS
              value: "/kafka-logs"

          volumeMounts:
            - name: logs
              mountPath: /kafka-logs
              subPath: logs
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        storageClassName: "longhorn"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
